package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	StockStore stockStorePersistedState `json:"stockStore"`
}

type stockStorePersistedState struct {
	ItemSeq int `json:"itemSeq"`
	MovementSeq int `json:"movementSeq"`
	EventSeq int `json:"eventSeq"`
	Items []stockItem `json:"items"`
	Movements []stockMovement `json:"movements"`
	Events []stockEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	stockStore.RLock()
	state.StockStore = stockStorePersistedState{
		ItemSeq: stockStore.itemSeq,
		MovementSeq: stockStore.movementSeq,
		EventSeq: stockStore.eventSeq,
		Items: stockStore.items,
		Movements: stockStore.movements,
		Events: stockStore.events,
	}
	stockStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	stockStore.Lock()
	stockStore.itemSeq = state.StockStore.ItemSeq
	stockStore.movementSeq = state.StockStore.MovementSeq
	stockStore.eventSeq = state.StockStore.EventSeq
	stockStore.items = state.StockStore.Items
	stockStore.movements = state.StockStore.Movements
	stockStore.events = state.StockStore.Events
	stockStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	stockStore.Lock()
	stockStore.itemSeq = state.StockStore.ItemSeq
	stockStore.movementSeq = state.StockStore.MovementSeq
	stockStore.eventSeq = state.StockStore.EventSeq
	stockStore.items = state.StockStore.Items
	stockStore.movements = state.StockStore.Movements
	stockStore.events = state.StockStore.Events
	stockStore.Unlock()
}
