package httptransport

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	StockStore stockStorePersistedState `json:"stockStore"`
}

type stockStorePersistedState struct {
	ItemSeq     int             `json:"itemSeq"`
	MovementSeq int             `json:"movementSeq"`
	EventSeq    int             `json:"eventSeq"`
	Items       []stockItem     `json:"items"`
	Movements   []stockMovement `json:"movements"`
	Events      []stockEvent    `json:"events"`
}

var initialPersistedState persistedState

func init() {
	raw, err := capturePersistedState()
	if err != nil {
		panic(fmt.Sprintf("capture initial persisted state: %v", err))
	}
	initialPersistedState = mustDecodePersistedState(raw)
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	stockStore.RLock()
	itemSeq := maxSequence(stockStore.itemSeq, maxStockItemSequence(stockStore.items))
	movementSeq := maxSequence(stockStore.movementSeq, maxStockMovementSequence(stockStore.movements))
	eventSeq := maxSequence(stockStore.eventSeq, maxStockEventSequence(stockStore.events))
	state.StockStore = stockStorePersistedState{
		ItemSeq:     itemSeq,
		MovementSeq: movementSeq,
		EventSeq:    eventSeq,
		Items:       stockStore.items,
		Movements:   stockStore.movements,
		Events:      stockStore.events,
	}
	stockStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	state, err := decodePersistedState(raw)
	if err != nil {
		return err
	}
	stockStore.Lock()
	stockStore.itemSeq = state.StockStore.ItemSeq
	stockStore.movementSeq = state.StockStore.MovementSeq
	stockStore.eventSeq = state.StockStore.EventSeq
	stockStore.items = state.StockStore.Items
	stockStore.movements = state.StockStore.Movements
	stockStore.events = state.StockStore.Events
	syncStockStoreSequencesLocked()
	stockStore.Unlock()
	return nil
}

func resetPersistedState() {
	state := clonePersistedState(initialPersistedState)
	stockStore.Lock()
	stockStore.itemSeq = state.StockStore.ItemSeq
	stockStore.movementSeq = state.StockStore.MovementSeq
	stockStore.eventSeq = state.StockStore.EventSeq
	stockStore.items = state.StockStore.Items
	stockStore.movements = state.StockStore.Movements
	stockStore.events = state.StockStore.Events
	syncStockStoreSequencesLocked()
	stockStore.Unlock()
}

func restorePersistedStockItems(items []stockItem) bool {
	if len(items) == 0 {
		return false
	}

	stockStore.Lock()
	stockStore.itemSeq = 0
	stockStore.movementSeq = 0
	stockStore.eventSeq = 0
	stockStore.items = append([]stockItem(nil), items...)
	stockStore.movements = nil
	stockStore.events = nil
	syncStockStoreSequencesLocked()
	stockStore.Unlock()
	return true
}

func restorePersistedEntities(rawEntities [][]byte) (bool, error) {
	if len(rawEntities) == 0 {
		return false, nil
	}

	items := make([]stockItem, 0, len(rawEntities))
	for _, raw := range rawEntities {
		var item stockItem
		if err := json.Unmarshal(raw, &item); err != nil {
			return false, fmt.Errorf("unmarshal persisted entity: %w", err)
		}
		items = append(items, item)
	}

	return restorePersistedStockItems(items), nil
}

func decodePersistedState(raw []byte) (persistedState, error) {
	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return persistedState{}, fmt.Errorf("unmarshal persisted state: %w", err)
	}
	return state, nil
}

func mustDecodePersistedState(raw []byte) persistedState {
	state, err := decodePersistedState(raw)
	if err != nil {
		panic(err)
	}
	return state
}

func clonePersistedState(state persistedState) persistedState {
	raw, err := json.Marshal(state)
	if err != nil {
		panic(fmt.Sprintf("marshal persisted state clone: %v", err))
	}
	return mustDecodePersistedState(raw)
}

func syncStockStoreSequencesLocked() {
	stockStore.itemSeq = maxSequence(stockStore.itemSeq, maxStockItemSequence(stockStore.items))
	stockStore.movementSeq = maxSequence(stockStore.movementSeq, maxStockMovementSequence(stockStore.movements))
	stockStore.eventSeq = maxSequence(stockStore.eventSeq, maxStockEventSequence(stockStore.events))
}

func maxStockItemSequence(items []stockItem) int {
	maxID := 0
	for _, item := range items {
		maxID = maxSequence(maxID, parseNumericSuffix(item.ID, "st-"))
	}
	return maxID
}

func maxStockMovementSequence(items []stockMovement) int {
	maxID := 0
	for _, item := range items {
		maxID = maxSequence(maxID, parseNumericSuffix(item.ID, "mv-"))
	}
	return maxID
}

func maxStockEventSequence(items []stockEvent) int {
	maxID := 0
	for _, item := range items {
		maxID = maxSequence(maxID, parseNumericSuffix(item.ID, "ise-"))
	}
	return maxID
}

func parseNumericSuffix(value, prefix string) int {
	value = strings.TrimSpace(value)
	if !strings.HasPrefix(value, prefix) {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimPrefix(value, prefix))
	if err != nil {
		return 0
	}
	return n
}

func maxSequence(current, candidate int) int {
	if candidate > current {
		return candidate
	}
	return current
}
