package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	LedgerStore ledgerStorePersistedState `json:"ledgerStore"`
}

type ledgerStorePersistedState struct {
	AccountSeq int             `json:"accountSeq"`
	EntrySeq   int             `json:"entrySeq"`
	EventSeq   int             `json:"eventSeq"`
	JournalSeq int             `json:"journalSeq"`
	LastHash   string          `json:"lastHash"`
	Accounts   []account       `json:"accounts"`
	Entries    []ledgerEntry   `json:"entries"`
	Events     []ledgerEvent   `json:"events"`
	Journal    []journalRecord `json:"journal"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	ledgerStore.RLock()
	state.LedgerStore = ledgerStorePersistedState{
		AccountSeq: ledgerStore.accountSeq,
		EntrySeq:   ledgerStore.entrySeq,
		EventSeq:   ledgerStore.eventSeq,
		JournalSeq: ledgerStore.journalSeq,
		LastHash:   ledgerStore.lastHash,
		Accounts:   ledgerStore.accounts,
		Entries:    ledgerStore.entries,
		Events:     ledgerStore.events,
		Journal:    ledgerStore.journal,
	}
	ledgerStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	ledgerStore.Lock()
	ledgerStore.accountSeq = state.LedgerStore.AccountSeq
	ledgerStore.entrySeq = state.LedgerStore.EntrySeq
	ledgerStore.eventSeq = state.LedgerStore.EventSeq
	ledgerStore.journalSeq = state.LedgerStore.JournalSeq
	ledgerStore.lastHash = state.LedgerStore.LastHash
	ledgerStore.accounts = state.LedgerStore.Accounts
	ledgerStore.entries = state.LedgerStore.Entries
	ledgerStore.events = state.LedgerStore.Events
	ledgerStore.journal = state.LedgerStore.Journal
	ledgerStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	ledgerStore.Lock()
	ledgerStore.accountSeq = state.LedgerStore.AccountSeq
	ledgerStore.entrySeq = state.LedgerStore.EntrySeq
	ledgerStore.eventSeq = state.LedgerStore.EventSeq
	ledgerStore.journalSeq = state.LedgerStore.JournalSeq
	ledgerStore.lastHash = state.LedgerStore.LastHash
	ledgerStore.accounts = state.LedgerStore.Accounts
	ledgerStore.entries = state.LedgerStore.Entries
	ledgerStore.events = state.LedgerStore.Events
	ledgerStore.journal = state.LedgerStore.Journal
	ledgerStore.Unlock()
}
