apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kis-nexus.fullname" . }}-settings
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

