package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	DiagnosticsStore diagnosticsStorePersistedState `json:"diagnosticsStore"`
}

type diagnosticsStorePersistedState struct {
	Seq int `json:"seq"`
	EventSeq int `json:"eventSeq"`
	Diagnostics []diagnostic `json:"diagnostics"`
	Events []diagnosticEvent `json:"events"`
	WarrantyData map[string]warrantyStatus `json:"warrantyData"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	diagnosticsStore.RLock()
	state.DiagnosticsStore = diagnosticsStorePersistedState{
		Seq: diagnosticsStore.seq,
		EventSeq: diagnosticsStore.eventSeq,
		Diagnostics: diagnosticsStore.diagnostics,
		Events: diagnosticsStore.events,
		WarrantyData: diagnosticsStore.warrantyData,
	}
	diagnosticsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	diagnosticsStore.Lock()
	diagnosticsStore.seq = state.DiagnosticsStore.Seq
	diagnosticsStore.eventSeq = state.DiagnosticsStore.EventSeq
	diagnosticsStore.diagnostics = state.DiagnosticsStore.Diagnostics
	diagnosticsStore.events = state.DiagnosticsStore.Events
	diagnosticsStore.warrantyData = state.DiagnosticsStore.WarrantyData
	diagnosticsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	diagnosticsStore.Lock()
	diagnosticsStore.seq = state.DiagnosticsStore.Seq
	diagnosticsStore.eventSeq = state.DiagnosticsStore.EventSeq
	diagnosticsStore.diagnostics = state.DiagnosticsStore.Diagnostics
	diagnosticsStore.events = state.DiagnosticsStore.Events
	diagnosticsStore.warrantyData = state.DiagnosticsStore.WarrantyData
	diagnosticsStore.Unlock()
}
