package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	AuditStore auditStorePersistedState `json:"auditStore"`
}

type auditStorePersistedState struct {
	TaskSeq       int                  `json:"taskSeq"`
	LineSeq       int                  `json:"lineSeq"`
	AdjustmentSeq int                  `json:"adjustmentSeq"`
	EventSeq      int                  `json:"eventSeq"`
	Tasks         []inventoryAuditTask `json:"tasks"`
	Lines         []inventoryCountLine `json:"lines"`
	Adjustments   []stockAdjustment    `json:"adjustments"`
	Events        []auditEvent         `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	auditStore.RLock()
	state.AuditStore = auditStorePersistedState{
		TaskSeq:       auditStore.taskSeq,
		LineSeq:       auditStore.lineSeq,
		AdjustmentSeq: auditStore.adjustmentSeq,
		EventSeq:      auditStore.eventSeq,
		Tasks:         auditStore.tasks,
		Lines:         auditStore.lines,
		Adjustments:   auditStore.adjustments,
		Events:        auditStore.events,
	}
	auditStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	auditStore.Lock()
	auditStore.taskSeq = state.AuditStore.TaskSeq
	auditStore.lineSeq = state.AuditStore.LineSeq
	auditStore.adjustmentSeq = state.AuditStore.AdjustmentSeq
	auditStore.eventSeq = state.AuditStore.EventSeq
	auditStore.tasks = state.AuditStore.Tasks
	auditStore.lines = state.AuditStore.Lines
	auditStore.adjustments = state.AuditStore.Adjustments
	auditStore.events = state.AuditStore.Events
	auditStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	auditStore.Lock()
	auditStore.taskSeq = state.AuditStore.TaskSeq
	auditStore.lineSeq = state.AuditStore.LineSeq
	auditStore.adjustmentSeq = state.AuditStore.AdjustmentSeq
	auditStore.eventSeq = state.AuditStore.EventSeq
	auditStore.tasks = state.AuditStore.Tasks
	auditStore.lines = state.AuditStore.Lines
	auditStore.adjustments = state.AuditStore.Adjustments
	auditStore.events = state.AuditStore.Events
	auditStore.Unlock()
}
