package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	AuditStore auditStorePersistedState `json:"auditStore"`
}

type auditStorePersistedState struct {
	Seq           int          `json:"seq"`
	LastHash      string       `json:"lastHash"`
	RetentionDays int          `json:"retentionDays"`
	Events        []auditEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	auditStore.RLock()
	state.AuditStore = auditStorePersistedState{
		Seq:           auditStore.seq,
		LastHash:      auditStore.lastHash,
		RetentionDays: auditStore.retentionDays,
		Events:        auditStore.events,
	}
	auditStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	auditStore.Lock()
	auditStore.seq = state.AuditStore.Seq
	auditStore.lastHash = state.AuditStore.LastHash
	auditStore.retentionDays = state.AuditStore.RetentionDays
	auditStore.events = state.AuditStore.Events
	auditStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	auditStore.Lock()
	auditStore.seq = state.AuditStore.Seq
	auditStore.lastHash = state.AuditStore.LastHash
	auditStore.retentionDays = state.AuditStore.RetentionDays
	auditStore.events = state.AuditStore.Events
	auditStore.Unlock()
}
