package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	CrmContactsStore crmContactsStorePersistedState `json:"crmContactsStore"`
}

type crmContactsStorePersistedState struct {
	ClientSeq int `json:"clientSeq"`
	ContactSeq int `json:"contactSeq"`
	InteractionSeq int `json:"interactionSeq"`
	Clients []client `json:"clients"`
	Contacts []contact `json:"contacts"`
	Interactions []interaction `json:"interactions"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	crmContactsStore.RLock()
	state.CrmContactsStore = crmContactsStorePersistedState{
		ClientSeq: crmContactsStore.clientSeq,
		ContactSeq: crmContactsStore.contactSeq,
		InteractionSeq: crmContactsStore.interactionSeq,
		Clients: crmContactsStore.clients,
		Contacts: crmContactsStore.contacts,
		Interactions: crmContactsStore.interactions,
	}
	crmContactsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	crmContactsStore.Lock()
	crmContactsStore.clientSeq = state.CrmContactsStore.ClientSeq
	crmContactsStore.contactSeq = state.CrmContactsStore.ContactSeq
	crmContactsStore.interactionSeq = state.CrmContactsStore.InteractionSeq
	crmContactsStore.clients = state.CrmContactsStore.Clients
	crmContactsStore.contacts = state.CrmContactsStore.Contacts
	crmContactsStore.interactions = state.CrmContactsStore.Interactions
	crmContactsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	crmContactsStore.Lock()
	crmContactsStore.clientSeq = state.CrmContactsStore.ClientSeq
	crmContactsStore.contactSeq = state.CrmContactsStore.ContactSeq
	crmContactsStore.interactionSeq = state.CrmContactsStore.InteractionSeq
	crmContactsStore.clients = state.CrmContactsStore.Clients
	crmContactsStore.contacts = state.CrmContactsStore.Contacts
	crmContactsStore.interactions = state.CrmContactsStore.Interactions
	crmContactsStore.Unlock()
}
