package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	SalesDocsStore salesDocsStorePersistedState `json:"salesDocsStore"`
}

type salesDocsStorePersistedState struct {
	Seq       int             `json:"seq"`
	EventSeq  int             `json:"eventSeq"`
	Templates []template      `json:"templates"`
	Documents []document      `json:"documents"`
	Events    []salesDocEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	salesDocsStore.RLock()
	state.SalesDocsStore = salesDocsStorePersistedState{
		Seq:       salesDocsStore.seq,
		EventSeq:  salesDocsStore.eventSeq,
		Templates: salesDocsStore.templates,
		Documents: salesDocsStore.documents,
		Events:    salesDocsStore.events,
	}
	salesDocsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	salesDocsStore.Lock()
	salesDocsStore.seq = state.SalesDocsStore.Seq
	salesDocsStore.eventSeq = state.SalesDocsStore.EventSeq
	salesDocsStore.templates = state.SalesDocsStore.Templates
	salesDocsStore.documents = state.SalesDocsStore.Documents
	salesDocsStore.events = state.SalesDocsStore.Events
	salesDocsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	salesDocsStore.Lock()
	salesDocsStore.seq = state.SalesDocsStore.Seq
	salesDocsStore.eventSeq = state.SalesDocsStore.EventSeq
	salesDocsStore.templates = state.SalesDocsStore.Templates
	salesDocsStore.documents = state.SalesDocsStore.Documents
	salesDocsStore.events = state.SalesDocsStore.Events
	salesDocsStore.Unlock()
}
