package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	IdentityStore identityStorePersistedState `json:"identityStore"`
}

type identityStorePersistedState struct {
	RoleSeq   int              `json:"roleSeq"`
	PolicySeq int              `json:"policySeq"`
	Roles     []role           `json:"roles"`
	Policies  []policy         `json:"policies"`
	Bindings  []subjectBinding `json:"bindings"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	identityStore.RLock()
	state.IdentityStore = identityStorePersistedState{
		RoleSeq:   identityStore.roleSeq,
		PolicySeq: identityStore.policySeq,
		Roles:     identityStore.roles,
		Policies:  identityStore.policies,
		Bindings:  identityStore.bindings,
	}
	identityStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	identityStore.Lock()
	identityStore.roleSeq = state.IdentityStore.RoleSeq
	identityStore.policySeq = state.IdentityStore.PolicySeq
	identityStore.roles = state.IdentityStore.Roles
	identityStore.policies = state.IdentityStore.Policies
	identityStore.bindings = state.IdentityStore.Bindings
	identityStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	identityStore.Lock()
	identityStore.roleSeq = state.IdentityStore.RoleSeq
	identityStore.policySeq = state.IdentityStore.PolicySeq
	identityStore.roles = state.IdentityStore.Roles
	identityStore.policies = state.IdentityStore.Policies
	identityStore.bindings = state.IdentityStore.Bindings
	identityStore.Unlock()
}
