package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	SalesDealsAuditStore       salesDealsAuditStorePersistedState       `json:"salesDealsAuditStore"`
	SalesDealsDomainEventStore salesDealsDomainEventStorePersistedState `json:"salesDealsDomainEventStore"`
	SalesDealsStore            salesDealsStorePersistedState            `json:"salesDealsStore"`
}

type salesDealsAuditStorePersistedState struct {
	Seq    int              `json:"seq"`
	Events []dealAuditEvent `json:"events"`
}

type salesDealsDomainEventStorePersistedState struct {
	Seq    int               `json:"seq"`
	Events []dealDomainEvent `json:"events"`
}

type salesDealsStorePersistedState struct {
	Seq        int           `json:"seq"`
	PaymentSeq int           `json:"paymentSeq"`
	Deals      []deal        `json:"deals"`
	Payments   []salePayment `json:"payments"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	salesDealsAuditStore.RLock()
	state.SalesDealsAuditStore = salesDealsAuditStorePersistedState{
		Seq:    salesDealsAuditStore.seq,
		Events: salesDealsAuditStore.events,
	}
	salesDealsAuditStore.RUnlock()
	salesDealsDomainEventStore.RLock()
	state.SalesDealsDomainEventStore = salesDealsDomainEventStorePersistedState{
		Seq:    salesDealsDomainEventStore.seq,
		Events: salesDealsDomainEventStore.events,
	}
	salesDealsDomainEventStore.RUnlock()
	salesDealsStore.RLock()
	state.SalesDealsStore = salesDealsStorePersistedState{
		Seq:        salesDealsStore.seq,
		PaymentSeq: salesDealsStore.paymentSeq,
		Deals:      salesDealsStore.deals,
		Payments:   salesDealsStore.payments,
	}
	salesDealsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	salesDealsAuditStore.Lock()
	salesDealsAuditStore.seq = state.SalesDealsAuditStore.Seq
	salesDealsAuditStore.events = state.SalesDealsAuditStore.Events
	salesDealsAuditStore.Unlock()
	salesDealsDomainEventStore.Lock()
	salesDealsDomainEventStore.seq = state.SalesDealsDomainEventStore.Seq
	salesDealsDomainEventStore.events = state.SalesDealsDomainEventStore.Events
	salesDealsDomainEventStore.Unlock()
	salesDealsStore.Lock()
	salesDealsStore.seq = state.SalesDealsStore.Seq
	salesDealsStore.paymentSeq = state.SalesDealsStore.PaymentSeq
	salesDealsStore.deals = state.SalesDealsStore.Deals
	salesDealsStore.payments = state.SalesDealsStore.Payments
	salesDealsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	salesDealsAuditStore.Lock()
	salesDealsAuditStore.seq = state.SalesDealsAuditStore.Seq
	salesDealsAuditStore.events = state.SalesDealsAuditStore.Events
	salesDealsAuditStore.Unlock()
	salesDealsDomainEventStore.Lock()
	salesDealsDomainEventStore.seq = state.SalesDealsDomainEventStore.Seq
	salesDealsDomainEventStore.events = state.SalesDealsDomainEventStore.Events
	salesDealsDomainEventStore.Unlock()
	salesDealsStore.Lock()
	salesDealsStore.seq = state.SalesDealsStore.Seq
	salesDealsStore.paymentSeq = state.SalesDealsStore.PaymentSeq
	salesDealsStore.deals = state.SalesDealsStore.Deals
	salesDealsStore.payments = state.SalesDealsStore.Payments
	salesDealsStore.Unlock()
}
