package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	ReceivingStore receivingStorePersistedState `json:"receivingStore"`
}

type receivingStorePersistedState struct {
	ReceiptSeq int `json:"receiptSeq"`
	LineSeq int `json:"lineSeq"`
	DiscrepancySeq int `json:"discrepancySeq"`
	TaskSeq int `json:"taskSeq"`
	EventSeq int `json:"eventSeq"`
	Receipts []receipt `json:"receipts"`
	Discrepancies []discrepancy `json:"discrepancies"`
	Tasks []warehouseTask `json:"tasks"`
	Events []receivingEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	receivingStore.RLock()
	state.ReceivingStore = receivingStorePersistedState{
		ReceiptSeq: receivingStore.receiptSeq,
		LineSeq: receivingStore.lineSeq,
		DiscrepancySeq: receivingStore.discrepancySeq,
		TaskSeq: receivingStore.taskSeq,
		EventSeq: receivingStore.eventSeq,
		Receipts: receivingStore.receipts,
		Discrepancies: receivingStore.discrepancies,
		Tasks: receivingStore.tasks,
		Events: receivingStore.events,
	}
	receivingStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	receivingStore.Lock()
	receivingStore.receiptSeq = state.ReceivingStore.ReceiptSeq
	receivingStore.lineSeq = state.ReceivingStore.LineSeq
	receivingStore.discrepancySeq = state.ReceivingStore.DiscrepancySeq
	receivingStore.taskSeq = state.ReceivingStore.TaskSeq
	receivingStore.eventSeq = state.ReceivingStore.EventSeq
	receivingStore.receipts = state.ReceivingStore.Receipts
	receivingStore.discrepancies = state.ReceivingStore.Discrepancies
	receivingStore.tasks = state.ReceivingStore.Tasks
	receivingStore.events = state.ReceivingStore.Events
	receivingStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	receivingStore.Lock()
	receivingStore.receiptSeq = state.ReceivingStore.ReceiptSeq
	receivingStore.lineSeq = state.ReceivingStore.LineSeq
	receivingStore.discrepancySeq = state.ReceivingStore.DiscrepancySeq
	receivingStore.taskSeq = state.ReceivingStore.TaskSeq
	receivingStore.eventSeq = state.ReceivingStore.EventSeq
	receivingStore.receipts = state.ReceivingStore.Receipts
	receivingStore.discrepancies = state.ReceivingStore.Discrepancies
	receivingStore.tasks = state.ReceivingStore.Tasks
	receivingStore.events = state.ReceivingStore.Events
	receivingStore.Unlock()
}
