package httptransport

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	ReportingStore reportingStorePersistedState `json:"reportingStore"`
}

type reportingStorePersistedState struct {
	ExportSeq int `json:"exportSeq"`
	ScheduleSeq int `json:"scheduleSeq"`
	EventSeq int `json:"eventSeq"`
	Exports []reportExport `json:"exports"`
	Schedules []reportSchedule `json:"schedules"`
	Metrics map[string]reportingMetric `json:"metrics"`
	Events []reportingEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	reportingStore.RLock()
	state.ReportingStore = reportingStorePersistedState{
		ExportSeq: reportingStore.exportSeq,
		ScheduleSeq: reportingStore.scheduleSeq,
		EventSeq: reportingStore.eventSeq,
		Exports: reportingStore.exports,
		Schedules: reportingStore.schedules,
		Metrics: reportingStore.metrics,
		Events: reportingStore.events,
	}
	reportingStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	reportingStore.Lock()
	reportingStore.exportSeq = state.ReportingStore.ExportSeq
	reportingStore.scheduleSeq = state.ReportingStore.ScheduleSeq
	reportingStore.eventSeq = state.ReportingStore.EventSeq
	reportingStore.exports = state.ReportingStore.Exports
	reportingStore.schedules = state.ReportingStore.Schedules
	reportingStore.metrics = state.ReportingStore.Metrics
	reportingStore.events = state.ReportingStore.Events
	reportingStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	reportingStore.Lock()
	reportingStore.exportSeq = state.ReportingStore.ExportSeq
	reportingStore.scheduleSeq = state.ReportingStore.ScheduleSeq
	reportingStore.eventSeq = state.ReportingStore.EventSeq
	reportingStore.exports = state.ReportingStore.Exports
	reportingStore.schedules = state.ReportingStore.Schedules
	reportingStore.metrics = state.ReportingStore.Metrics
	reportingStore.events = state.ReportingStore.Events
	reportingStore.Unlock()
}

func restorePersistedEntities(rawEntities [][]byte) (bool, error) {
	if len(rawEntities) == 0 {
		return false, nil
	}

	exports := make([]reportExport, 0, len(rawEntities))
	maxExportSeq := 0
	for _, raw := range rawEntities {
		var entity reportExport
		if err := json.Unmarshal(raw, &entity); err != nil {
			return false, fmt.Errorf("unmarshal persisted entity: %w", err)
		}
		exports = append(exports, entity)
		maxExportSeq = maxInt(maxExportSeq, parseNumericSuffix(entity.ID, "re-"))
	}

	reportingStore.Lock()
	reportingStore.exportSeq = maxExportSeq
	reportingStore.scheduleSeq = 0
	reportingStore.eventSeq = 0
	reportingStore.exports = append([]reportExport(nil), exports...)
	reportingStore.schedules = nil
	reportingStore.events = nil
	if reportingStore.metrics == nil {
		reportingStore.metrics = map[string]reportingMetric{}
	}
	reportingStore.Unlock()
	return true, nil
}

func parseNumericSuffix(value, prefix string) int {
	value = strings.TrimSpace(value)
	if !strings.HasPrefix(value, prefix) {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimPrefix(value, prefix))
	if err != nil {
		return 0
	}
	return n
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
