package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	CostingStore costingStorePersistedState `json:"costingStore"`
}

type costingStorePersistedState struct {
	Seq      int             `json:"seq"`
	ModelSeq int             `json:"modelSeq"`
	EventSeq int             `json:"eventSeq"`
	History  []costingResult `json:"history"`
	Models   []costingModel  `json:"models"`
	Events   []costingEvent  `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	costingStore.RLock()
	state.CostingStore = costingStorePersistedState{
		Seq:      costingStore.seq,
		ModelSeq: costingStore.modelSeq,
		EventSeq: costingStore.eventSeq,
		History:  costingStore.history,
		Models:   costingStore.models,
		Events:   costingStore.events,
	}
	costingStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	costingStore.Lock()
	costingStore.seq = state.CostingStore.Seq
	costingStore.modelSeq = state.CostingStore.ModelSeq
	costingStore.eventSeq = state.CostingStore.EventSeq
	costingStore.history = state.CostingStore.History
	costingStore.models = state.CostingStore.Models
	costingStore.events = state.CostingStore.Events
	costingStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	costingStore.Lock()
	costingStore.seq = state.CostingStore.Seq
	costingStore.modelSeq = state.CostingStore.ModelSeq
	costingStore.eventSeq = state.CostingStore.EventSeq
	costingStore.history = state.CostingStore.History
	costingStore.models = state.CostingStore.Models
	costingStore.events = state.CostingStore.Events
	costingStore.Unlock()
}
