package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	AppointmentStore appointmentStorePersistedState `json:"appointmentStore"`
}

type appointmentStorePersistedState struct {
	Seq int `json:"seq"`
	EventSeq int `json:"eventSeq"`
	Slots []slot `json:"slots"`
	Appointments []appointment `json:"appointments"`
	Events []appointmentEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	appointmentStore.RLock()
	state.AppointmentStore = appointmentStorePersistedState{
		Seq: appointmentStore.seq,
		EventSeq: appointmentStore.eventSeq,
		Slots: appointmentStore.slots,
		Appointments: appointmentStore.appointments,
		Events: appointmentStore.events,
	}
	appointmentStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	appointmentStore.Lock()
	appointmentStore.seq = state.AppointmentStore.Seq
	appointmentStore.eventSeq = state.AppointmentStore.EventSeq
	appointmentStore.slots = state.AppointmentStore.Slots
	appointmentStore.appointments = state.AppointmentStore.Appointments
	appointmentStore.events = state.AppointmentStore.Events
	appointmentStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	appointmentStore.Lock()
	appointmentStore.seq = state.AppointmentStore.Seq
	appointmentStore.eventSeq = state.AppointmentStore.EventSeq
	appointmentStore.slots = state.AppointmentStore.Slots
	appointmentStore.appointments = state.AppointmentStore.Appointments
	appointmentStore.events = state.AppointmentStore.Events
	appointmentStore.Unlock()
}
