package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	CrmLeadsStore crmLeadsStorePersistedState `json:"crmLeadsStore"`
}

type crmLeadsStorePersistedState struct {
	LeadSeq     int           `json:"leadSeq"`
	ActivitySeq int           `json:"activitySeq"`
	EventSeq    int           `json:"eventSeq"`
	Leads       []lead        `json:"leads"`
	Activities  []activity    `json:"activities"`
	Events      []domainEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	crmLeadsStore.RLock()
	state.CrmLeadsStore = crmLeadsStorePersistedState{
		LeadSeq:     crmLeadsStore.leadSeq,
		ActivitySeq: crmLeadsStore.activitySeq,
		EventSeq:    crmLeadsStore.eventSeq,
		Leads:       crmLeadsStore.leads,
		Activities:  crmLeadsStore.activities,
		Events:      crmLeadsStore.events,
	}
	crmLeadsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	crmLeadsStore.Lock()
	crmLeadsStore.leadSeq = state.CrmLeadsStore.LeadSeq
	crmLeadsStore.activitySeq = state.CrmLeadsStore.ActivitySeq
	crmLeadsStore.eventSeq = state.CrmLeadsStore.EventSeq
	crmLeadsStore.leads = state.CrmLeadsStore.Leads
	crmLeadsStore.activities = state.CrmLeadsStore.Activities
	crmLeadsStore.events = state.CrmLeadsStore.Events
	crmLeadsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	crmLeadsStore.Lock()
	crmLeadsStore.leadSeq = state.CrmLeadsStore.LeadSeq
	crmLeadsStore.activitySeq = state.CrmLeadsStore.ActivitySeq
	crmLeadsStore.eventSeq = state.CrmLeadsStore.EventSeq
	crmLeadsStore.leads = state.CrmLeadsStore.Leads
	crmLeadsStore.activities = state.CrmLeadsStore.Activities
	crmLeadsStore.events = state.CrmLeadsStore.Events
	crmLeadsStore.Unlock()
}
