package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	PartsStore partsStorePersistedState `json:"partsStore"`
}

type partsStorePersistedState struct {
	Seq int `json:"seq"`
	ProcurementSeq int `json:"procurementSeq"`
	EventSeq int `json:"eventSeq"`
	Usages []partsUsage `json:"usages"`
	StockByPartCode map[string]partStock `json:"stockByPartCode"`
	Procurements []procurementRequest `json:"procurements"`
	Events []partsDomainEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	partsStore.RLock()
	state.PartsStore = partsStorePersistedState{
		Seq: partsStore.seq,
		ProcurementSeq: partsStore.procurementSeq,
		EventSeq: partsStore.eventSeq,
		Usages: partsStore.usages,
		StockByPartCode: partsStore.stockByPartCode,
		Procurements: partsStore.procurements,
		Events: partsStore.events,
	}
	partsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	partsStore.Lock()
	partsStore.seq = state.PartsStore.Seq
	partsStore.procurementSeq = state.PartsStore.ProcurementSeq
	partsStore.eventSeq = state.PartsStore.EventSeq
	partsStore.usages = state.PartsStore.Usages
	partsStore.stockByPartCode = state.PartsStore.StockByPartCode
	partsStore.procurements = state.PartsStore.Procurements
	partsStore.events = state.PartsStore.Events
	partsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	partsStore.Lock()
	partsStore.seq = state.PartsStore.Seq
	partsStore.procurementSeq = state.PartsStore.ProcurementSeq
	partsStore.eventSeq = state.PartsStore.EventSeq
	partsStore.usages = state.PartsStore.Usages
	partsStore.stockByPartCode = state.PartsStore.StockByPartCode
	partsStore.procurements = state.PartsStore.Procurements
	partsStore.events = state.PartsStore.Events
	partsStore.Unlock()
}
