package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	FinanceInvoicingStore financeInvoicingStorePersistedState `json:"financeInvoicingStore"`
}

type financeInvoicingStorePersistedState struct {
	InvoiceSeq int `json:"invoiceSeq"`
	PaymentSeq int `json:"paymentSeq"`
	EventSeq int `json:"eventSeq"`
	Invoices []invoice `json:"invoices"`
	Payments []payment `json:"payments"`
	Events []invoicingEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	financeInvoicingStore.RLock()
	state.FinanceInvoicingStore = financeInvoicingStorePersistedState{
		InvoiceSeq: financeInvoicingStore.invoiceSeq,
		PaymentSeq: financeInvoicingStore.paymentSeq,
		EventSeq: financeInvoicingStore.eventSeq,
		Invoices: financeInvoicingStore.invoices,
		Payments: financeInvoicingStore.payments,
		Events: financeInvoicingStore.events,
	}
	financeInvoicingStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	financeInvoicingStore.Lock()
	financeInvoicingStore.invoiceSeq = state.FinanceInvoicingStore.InvoiceSeq
	financeInvoicingStore.paymentSeq = state.FinanceInvoicingStore.PaymentSeq
	financeInvoicingStore.eventSeq = state.FinanceInvoicingStore.EventSeq
	financeInvoicingStore.invoices = state.FinanceInvoicingStore.Invoices
	financeInvoicingStore.payments = state.FinanceInvoicingStore.Payments
	financeInvoicingStore.events = state.FinanceInvoicingStore.Events
	financeInvoicingStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	financeInvoicingStore.Lock()
	financeInvoicingStore.invoiceSeq = state.FinanceInvoicingStore.InvoiceSeq
	financeInvoicingStore.paymentSeq = state.FinanceInvoicingStore.PaymentSeq
	financeInvoicingStore.eventSeq = state.FinanceInvoicingStore.EventSeq
	financeInvoicingStore.invoices = state.FinanceInvoicingStore.Invoices
	financeInvoicingStore.payments = state.FinanceInvoicingStore.Payments
	financeInvoicingStore.events = state.FinanceInvoicingStore.Events
	financeInvoicingStore.Unlock()
}
