package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	WorkorderAuditStore workorderAuditStorePersistedState `json:"workorderAuditStore"`
	WorkorderNotificationStore workorderNotificationStorePersistedState `json:"workorderNotificationStore"`
	WorkorderStore workorderStorePersistedState `json:"workorderStore"`
}

type workorderAuditStorePersistedState struct {
	Seq int `json:"seq"`
	Events []workorderAuditEvent `json:"events"`
}

type workorderNotificationStorePersistedState struct {
	Seq int `json:"seq"`
	Notifications []workorderNotification `json:"notifications"`
}

type workorderStorePersistedState struct {
	Seq int `json:"seq"`
	Workorders []workorder `json:"workorders"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	workorderAuditStore.RLock()
	state.WorkorderAuditStore = workorderAuditStorePersistedState{
		Seq: workorderAuditStore.seq,
		Events: workorderAuditStore.events,
	}
	workorderAuditStore.RUnlock()
	workorderNotificationStore.RLock()
	state.WorkorderNotificationStore = workorderNotificationStorePersistedState{
		Seq: workorderNotificationStore.seq,
		Notifications: workorderNotificationStore.notifications,
	}
	workorderNotificationStore.RUnlock()
	workorderStore.RLock()
	state.WorkorderStore = workorderStorePersistedState{
		Seq: workorderStore.seq,
		Workorders: workorderStore.workorders,
	}
	workorderStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	workorderAuditStore.Lock()
	workorderAuditStore.seq = state.WorkorderAuditStore.Seq
	workorderAuditStore.events = state.WorkorderAuditStore.Events
	workorderAuditStore.Unlock()
	workorderNotificationStore.Lock()
	workorderNotificationStore.seq = state.WorkorderNotificationStore.Seq
	workorderNotificationStore.notifications = state.WorkorderNotificationStore.Notifications
	workorderNotificationStore.Unlock()
	workorderStore.Lock()
	workorderStore.seq = state.WorkorderStore.Seq
	workorderStore.workorders = state.WorkorderStore.Workorders
	workorderStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	workorderAuditStore.Lock()
	workorderAuditStore.seq = state.WorkorderAuditStore.Seq
	workorderAuditStore.events = state.WorkorderAuditStore.Events
	workorderAuditStore.Unlock()
	workorderNotificationStore.Lock()
	workorderNotificationStore.seq = state.WorkorderNotificationStore.Seq
	workorderNotificationStore.notifications = state.WorkorderNotificationStore.Notifications
	workorderNotificationStore.Unlock()
	workorderStore.Lock()
	workorderStore.seq = state.WorkorderStore.Seq
	workorderStore.workorders = state.WorkorderStore.Workorders
	workorderStore.Unlock()
}
