package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	CatalogStore catalogStorePersistedState `json:"catalogStore"`
}

type catalogStorePersistedState struct {
	CarSeq int `json:"carSeq"`
	PartSeq int `json:"partSeq"`
	EventSeq int `json:"eventSeq"`
	Cars []carModel `json:"cars"`
	Parts []partItem `json:"parts"`
	Events []catalogEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	catalogStore.RLock()
	state.CatalogStore = catalogStorePersistedState{
		CarSeq: catalogStore.carSeq,
		PartSeq: catalogStore.partSeq,
		EventSeq: catalogStore.eventSeq,
		Cars: catalogStore.cars,
		Parts: catalogStore.parts,
		Events: catalogStore.events,
	}
	catalogStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	catalogStore.Lock()
	catalogStore.carSeq = state.CatalogStore.CarSeq
	catalogStore.partSeq = state.CatalogStore.PartSeq
	catalogStore.eventSeq = state.CatalogStore.EventSeq
	catalogStore.cars = state.CatalogStore.Cars
	catalogStore.parts = state.CatalogStore.Parts
	catalogStore.events = state.CatalogStore.Events
	catalogStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	catalogStore.Lock()
	catalogStore.carSeq = state.CatalogStore.CarSeq
	catalogStore.partSeq = state.CatalogStore.PartSeq
	catalogStore.eventSeq = state.CatalogStore.EventSeq
	catalogStore.cars = state.CatalogStore.Cars
	catalogStore.parts = state.CatalogStore.Parts
	catalogStore.events = state.CatalogStore.Events
	catalogStore.Unlock()
}
