package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	BillingStore billingStorePersistedState `json:"billingStore"`
}

type billingStorePersistedState struct {
	InvoiceSeq int `json:"invoiceSeq"`
	ActSeq int `json:"actSeq"`
	PaymentSeq int `json:"paymentSeq"`
	EventSeq int `json:"eventSeq"`
	Invoices []serviceInvoice `json:"invoices"`
	Acts []completionAct `json:"acts"`
	Payments []servicePayment `json:"payments"`
	Events []billingEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	billingStore.RLock()
	state.BillingStore = billingStorePersistedState{
		InvoiceSeq: billingStore.invoiceSeq,
		ActSeq: billingStore.actSeq,
		PaymentSeq: billingStore.paymentSeq,
		EventSeq: billingStore.eventSeq,
		Invoices: billingStore.invoices,
		Acts: billingStore.acts,
		Payments: billingStore.payments,
		Events: billingStore.events,
	}
	billingStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	billingStore.Lock()
	billingStore.invoiceSeq = state.BillingStore.InvoiceSeq
	billingStore.actSeq = state.BillingStore.ActSeq
	billingStore.paymentSeq = state.BillingStore.PaymentSeq
	billingStore.eventSeq = state.BillingStore.EventSeq
	billingStore.invoices = state.BillingStore.Invoices
	billingStore.acts = state.BillingStore.Acts
	billingStore.payments = state.BillingStore.Payments
	billingStore.events = state.BillingStore.Events
	billingStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	billingStore.Lock()
	billingStore.invoiceSeq = state.BillingStore.InvoiceSeq
	billingStore.actSeq = state.BillingStore.ActSeq
	billingStore.paymentSeq = state.BillingStore.PaymentSeq
	billingStore.eventSeq = state.BillingStore.EventSeq
	billingStore.invoices = state.BillingStore.Invoices
	billingStore.acts = state.BillingStore.Acts
	billingStore.payments = state.BillingStore.Payments
	billingStore.events = state.BillingStore.Events
	billingStore.Unlock()
}
