package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	ProcurementStore procurementStorePersistedState `json:"procurementStore"`
}

type procurementStorePersistedState struct {
	RequestSeq int                  `json:"requestSeq"`
	OrderSeq   int                  `json:"orderSeq"`
	EventSeq   int                  `json:"eventSeq"`
	Policies   []procurementPolicy  `json:"policies"`
	Requests   []procurementRequest `json:"requests"`
	Orders     []purchaseOrder      `json:"orders"`
	Events     []procurementEvent   `json:"events"`
}

var initialPersistedState persistedState

func init() {
	raw, err := capturePersistedState()
	if err != nil {
		panic(fmt.Sprintf("capture initial persisted state: %v", err))
	}
	initialPersistedState = mustDecodePersistedState(raw)
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	procurementStore.RLock()
	state.ProcurementStore = procurementStorePersistedState{
		RequestSeq: procurementStore.requestSeq,
		OrderSeq:   procurementStore.orderSeq,
		EventSeq:   procurementStore.eventSeq,
		Policies:   procurementStore.policies,
		Requests:   procurementStore.requests,
		Orders:     procurementStore.orders,
		Events:     procurementStore.events,
	}
	procurementStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	state, err := decodePersistedState(raw)
	if err != nil {
		return err
	}
	procurementStore.Lock()
	procurementStore.requestSeq = state.ProcurementStore.RequestSeq
	procurementStore.orderSeq = state.ProcurementStore.OrderSeq
	procurementStore.eventSeq = state.ProcurementStore.EventSeq
	procurementStore.policies = state.ProcurementStore.Policies
	procurementStore.requests = state.ProcurementStore.Requests
	procurementStore.orders = state.ProcurementStore.Orders
	procurementStore.events = state.ProcurementStore.Events
	procurementStore.Unlock()
	return nil
}

func resetPersistedState() {
	state := clonePersistedState(initialPersistedState)
	procurementStore.Lock()
	procurementStore.requestSeq = state.ProcurementStore.RequestSeq
	procurementStore.orderSeq = state.ProcurementStore.OrderSeq
	procurementStore.eventSeq = state.ProcurementStore.EventSeq
	procurementStore.policies = state.ProcurementStore.Policies
	procurementStore.requests = state.ProcurementStore.Requests
	procurementStore.orders = state.ProcurementStore.Orders
	procurementStore.events = state.ProcurementStore.Events
	procurementStore.Unlock()
}

func decodePersistedState(raw []byte) (persistedState, error) {
	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return persistedState{}, fmt.Errorf("unmarshal persisted state: %w", err)
	}
	return state, nil
}

func mustDecodePersistedState(raw []byte) persistedState {
	state, err := decodePersistedState(raw)
	if err != nil {
		panic(err)
	}
	return state
}

func clonePersistedState(state persistedState) persistedState {
	raw, err := json.Marshal(state)
	if err != nil {
		panic(fmt.Sprintf("marshal persisted state clone: %v", err))
	}
	return mustDecodePersistedState(raw)
}
