package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	GatewayStore gatewayStorePersistedState `json:"gatewayStore"`
}

type gatewayStorePersistedState struct {
	RouteSeq    int                              `json:"routeSeq"`
	ContractSeq int                              `json:"contractSeq"`
	SagaSeq     int                              `json:"sagaSeq"`
	ReleaseSeq  int                              `json:"releaseSeq"`
	EventSeq    int                              `json:"eventSeq"`
	Routes      []gatewayRoute                   `json:"routes"`
	Contracts   []eventContract                  `json:"contracts"`
	Sagas       []sagaTemplate                   `json:"sagas"`
	Releases    []releasePlan                    `json:"releases"`
	Events      []gatewayEvent                   `json:"events"`
	RateCounter map[string]int                   `json:"rateCounter"`
	EntityStore map[string][]gatewayEntityRecord `json:"entityStore"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	gatewayStore.RLock()
	state.GatewayStore = gatewayStorePersistedState{
		RouteSeq:    gatewayStore.routeSeq,
		ContractSeq: gatewayStore.contractSeq,
		SagaSeq:     gatewayStore.sagaSeq,
		ReleaseSeq:  gatewayStore.releaseSeq,
		EventSeq:    gatewayStore.eventSeq,
		Routes:      gatewayStore.routes,
		Contracts:   gatewayStore.contracts,
		Sagas:       gatewayStore.sagas,
		Releases:    gatewayStore.releases,
		Events:      gatewayStore.events,
		RateCounter: gatewayStore.rateCounter,
		EntityStore: gatewayStore.entityStore,
	}
	gatewayStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	gatewayStore.Lock()
	gatewayStore.routeSeq = state.GatewayStore.RouteSeq
	gatewayStore.contractSeq = state.GatewayStore.ContractSeq
	gatewayStore.sagaSeq = state.GatewayStore.SagaSeq
	gatewayStore.releaseSeq = state.GatewayStore.ReleaseSeq
	gatewayStore.eventSeq = state.GatewayStore.EventSeq
	gatewayStore.routes = state.GatewayStore.Routes
	gatewayStore.contracts = state.GatewayStore.Contracts
	gatewayStore.sagas = state.GatewayStore.Sagas
	gatewayStore.releases = state.GatewayStore.Releases
	gatewayStore.events = state.GatewayStore.Events
	gatewayStore.rateCounter = state.GatewayStore.RateCounter
	gatewayStore.entityStore = state.GatewayStore.EntityStore
	gatewayStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	gatewayStore.Lock()
	gatewayStore.routeSeq = state.GatewayStore.RouteSeq
	gatewayStore.contractSeq = state.GatewayStore.ContractSeq
	gatewayStore.sagaSeq = state.GatewayStore.SagaSeq
	gatewayStore.releaseSeq = state.GatewayStore.ReleaseSeq
	gatewayStore.eventSeq = state.GatewayStore.EventSeq
	gatewayStore.routes = state.GatewayStore.Routes
	gatewayStore.contracts = state.GatewayStore.Contracts
	gatewayStore.sagas = state.GatewayStore.Sagas
	gatewayStore.releases = state.GatewayStore.Releases
	gatewayStore.events = state.GatewayStore.Events
	gatewayStore.rateCounter = state.GatewayStore.RateCounter
	gatewayStore.entityStore = state.GatewayStore.EntityStore
	gatewayStore.Unlock()
}
