package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	BiStore biStorePersistedState `json:"biStore"`
}

type biStorePersistedState struct {
	KpiSeq int `json:"kpiSeq"`
	SloSeq int `json:"sloSeq"`
	AlertSeq int `json:"alertSeq"`
	BackupSeq int `json:"backupSeq"`
	DeliverySeq int `json:"deliverySeq"`
	EventSeq int `json:"eventSeq"`
	Kpis []kpiSnapshot `json:"kpis"`
	Slos []sloDefinition `json:"slos"`
	Alerts []alertRule `json:"alerts"`
	Backups []backupJob `json:"backups"`
	Runbooks []runbook `json:"runbooks"`
	Deliveries []deliveryPlan `json:"deliveries"`
	Finops []finopsMetric `json:"finops"`
	Events []biEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	biStore.RLock()
	state.BiStore = biStorePersistedState{
		KpiSeq: biStore.kpiSeq,
		SloSeq: biStore.sloSeq,
		AlertSeq: biStore.alertSeq,
		BackupSeq: biStore.backupSeq,
		DeliverySeq: biStore.deliverySeq,
		EventSeq: biStore.eventSeq,
		Kpis: biStore.kpis,
		Slos: biStore.slos,
		Alerts: biStore.alerts,
		Backups: biStore.backups,
		Runbooks: biStore.runbooks,
		Deliveries: biStore.deliveries,
		Finops: biStore.finops,
		Events: biStore.events,
	}
	biStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	biStore.Lock()
	biStore.kpiSeq = state.BiStore.KpiSeq
	biStore.sloSeq = state.BiStore.SloSeq
	biStore.alertSeq = state.BiStore.AlertSeq
	biStore.backupSeq = state.BiStore.BackupSeq
	biStore.deliverySeq = state.BiStore.DeliverySeq
	biStore.eventSeq = state.BiStore.EventSeq
	biStore.kpis = state.BiStore.Kpis
	biStore.slos = state.BiStore.Slos
	biStore.alerts = state.BiStore.Alerts
	biStore.backups = state.BiStore.Backups
	biStore.runbooks = state.BiStore.Runbooks
	biStore.deliveries = state.BiStore.Deliveries
	biStore.finops = state.BiStore.Finops
	biStore.events = state.BiStore.Events
	biStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	biStore.Lock()
	biStore.kpiSeq = state.BiStore.KpiSeq
	biStore.sloSeq = state.BiStore.SloSeq
	biStore.alertSeq = state.BiStore.AlertSeq
	biStore.backupSeq = state.BiStore.BackupSeq
	biStore.deliverySeq = state.BiStore.DeliverySeq
	biStore.eventSeq = state.BiStore.EventSeq
	biStore.kpis = state.BiStore.Kpis
	biStore.slos = state.BiStore.Slos
	biStore.alerts = state.BiStore.Alerts
	biStore.backups = state.BiStore.Backups
	biStore.runbooks = state.BiStore.Runbooks
	biStore.deliveries = state.BiStore.Deliveries
	biStore.finops = state.BiStore.Finops
	biStore.events = state.BiStore.Events
	biStore.Unlock()
}
