package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	LaborCatalogStore laborCatalogStorePersistedState `json:"laborCatalogStore"`
}

type laborCatalogStorePersistedState struct {
	EventSeq int                 `json:"eventSeq"`
	Items    []laborItem         `json:"items"`
	Events   []laborCatalogEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	laborCatalogStore.RLock()
	state.LaborCatalogStore = laborCatalogStorePersistedState{
		EventSeq: laborCatalogStore.eventSeq,
		Items:    laborCatalogStore.items,
		Events:   laborCatalogStore.events,
	}
	laborCatalogStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	laborCatalogStore.Lock()
	laborCatalogStore.eventSeq = state.LaborCatalogStore.EventSeq
	laborCatalogStore.items = state.LaborCatalogStore.Items
	laborCatalogStore.events = state.LaborCatalogStore.Events
	laborCatalogStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	laborCatalogStore.Lock()
	laborCatalogStore.eventSeq = state.LaborCatalogStore.EventSeq
	laborCatalogStore.items = state.LaborCatalogStore.Items
	laborCatalogStore.events = state.LaborCatalogStore.Events
	laborCatalogStore.Unlock()
}
