package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	NotificationStore notificationStorePersistedState `json:"notificationStore"`
}

type notificationStorePersistedState struct {
	Seq int `json:"seq"`
	Jobs []notificationJob `json:"jobs"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	notificationStore.RLock()
	state.NotificationStore = notificationStorePersistedState{
		Seq: notificationStore.seq,
		Jobs: notificationStore.jobs,
	}
	notificationStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	notificationStore.Lock()
	notificationStore.seq = state.NotificationStore.Seq
	notificationStore.jobs = state.NotificationStore.Jobs
	notificationStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	notificationStore.Lock()
	notificationStore.seq = state.NotificationStore.Seq
	notificationStore.jobs = state.NotificationStore.Jobs
	notificationStore.Unlock()
}
