package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type storeField struct {
	Name         string
	ExportedName string
	TypeExpr     string
}

type storeSpec struct {
	VarName         string
	StateStructName string
	RootFieldName   string
	Fields          []storeField
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail("resolve working directory: %v", err)
	}

	runtimeTemplateText, err := loadRuntimeTemplate(root)
	if err != nil {
		fail("load runtime template: %v", err)
	}

	servicesDir := filepath.Join(root, "services")
	serviceEntries, err := os.ReadDir(servicesDir)
	if err != nil {
		fail("read services dir: %v", err)
	}

	updated := 0
	for _, entry := range serviceEntries {
		if !entry.IsDir() {
			continue
		}

		serviceName := entry.Name()
		serviceDir := filepath.Join(servicesDir, serviceName)
		handlersPath := filepath.Join(serviceDir, "internal", "transport", "http", "handlers.go")
		if _, err := os.Stat(handlersPath); err != nil {
			continue
		}

		stores, err := parseStores(handlersPath)
		if err != nil {
			fail("parse stores for %s: %v", serviceName, err)
		}
		stateFilePath := filepath.Join(serviceDir, "internal", "transport", "http", "persistence_state_gen.go")
		if err := os.WriteFile(stateFilePath, []byte(renderStateFile(stores)), 0o644); err != nil {
			fail("write %s: %v", stateFilePath, err)
		}

		runtimeFilePath := filepath.Join(serviceDir, "internal", "transport", "http", "persistence_runtime.go")
		if err := os.WriteFile(runtimeFilePath, []byte(runtimeTemplateText), 0o644); err != nil {
			fail("write %s: %v", runtimeFilePath, err)
		}

		mainPath := filepath.Join(serviceDir, "cmd", "api", "main.go")
		if err := patchMain(mainPath, serviceName); err != nil {
			fail("patch %s: %v", mainPath, err)
		}

		updated++
		fmt.Printf("updated %s\n", serviceName)
	}

	fmt.Printf("done: %d service(s) updated\n", updated)
}

func parseStores(handlersPath string) ([]storeSpec, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, handlersPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse file: %w", err)
	}

	var stores []storeSpec
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}

		for _, spec := range gen.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) != 1 || len(valueSpec.Values) != 1 {
				continue
			}

			varName := valueSpec.Names[0].Name
			if !strings.HasSuffix(varName, "Store") {
				continue
			}

			composite, ok := valueSpec.Values[0].(*ast.CompositeLit)
			if !ok {
				continue
			}

			structType, ok := composite.Type.(*ast.StructType)
			if !ok {
				continue
			}

			fields := make([]storeField, 0)
			for _, field := range structType.Fields.List {
				// Skip anonymous fields such as sync.RWMutex.
				if len(field.Names) == 0 {
					continue
				}

				typeExpr := exprToString(fset, field.Type)
				for _, name := range field.Names {
					fields = append(fields, storeField{
						Name:         name.Name,
						ExportedName: exportName(name.Name),
						TypeExpr:     typeExpr,
					})
				}
			}

			stores = append(stores, storeSpec{
				VarName:         varName,
				StateStructName: varName + "PersistedState",
				RootFieldName:   exportName(varName),
				Fields:          fields,
			})
		}
	}

	sort.Slice(stores, func(i, j int) bool {
		return stores[i].VarName < stores[j].VarName
	})
	return stores, nil
}

func exprToString(fset *token.FileSet, expr ast.Expr) string {
	var b bytes.Buffer
	_ = printer.Fprint(&b, fset, expr)
	return b.String()
}

func exportName(value string) string {
	if value == "" {
		return value
	}

	parts := strings.Split(value, "_")
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	name := strings.Join(parts, "")
	if name == "" {
		return "X"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func renderStateFile(stores []storeSpec) string {
	var b strings.Builder
	b.WriteString("package httptransport\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.\n")
	b.WriteString("type persistedState struct {\n")
	for _, store := range stores {
		b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", store.RootFieldName, store.StateStructName, store.VarName))
	}
	b.WriteString("}\n\n")

	for _, store := range stores {
		b.WriteString(fmt.Sprintf("type %s struct {\n", store.StateStructName))
		for _, field := range store.Fields {
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", field.ExportedName, field.TypeExpr, field.Name))
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("func capturePersistedState() ([]byte, error) {\n")
	b.WriteString("\tstate := persistedState{}\n")
	for _, store := range stores {
		b.WriteString(fmt.Sprintf("\t%s.RLock()\n", store.VarName))
		b.WriteString(fmt.Sprintf("\tstate.%s = %s{\n", store.RootFieldName, store.StateStructName))
		for _, field := range store.Fields {
			b.WriteString(fmt.Sprintf("\t\t%s: %s.%s,\n", field.ExportedName, store.VarName, field.Name))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s.RUnlock()\n", store.VarName))
	}
	b.WriteString("\traw, err := json.Marshal(state)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"marshal persisted state: %w\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn raw, nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func restorePersistedState(raw []byte) error {\n")
	b.WriteString("\tif len(raw) == 0 {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tvar state persistedState\n")
	b.WriteString("\tif err := json.Unmarshal(raw, &state); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"unmarshal persisted state: %w\", err)\n")
	b.WriteString("\t}\n")
	for _, store := range stores {
		b.WriteString(fmt.Sprintf("\t%s.Lock()\n", store.VarName))
		for _, field := range store.Fields {
			b.WriteString(fmt.Sprintf("\t%s.%s = state.%s.%s\n", store.VarName, field.Name, store.RootFieldName, field.ExportedName))
		}
		b.WriteString(fmt.Sprintf("\t%s.Unlock()\n", store.VarName))
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	b.WriteString("\nfunc resetPersistedState() {\n")
	if len(stores) > 0 {
		b.WriteString("\tvar state persistedState\n")
	}
	for _, store := range stores {
		b.WriteString(fmt.Sprintf("\t%s.Lock()\n", store.VarName))
		for _, field := range store.Fields {
			b.WriteString(fmt.Sprintf("\t%s.%s = state.%s.%s\n", store.VarName, field.Name, store.RootFieldName, field.ExportedName))
		}
		b.WriteString(fmt.Sprintf("\t%s.Unlock()\n", store.VarName))
	}
	b.WriteString("}\n")

	return b.String()
}

func patchMain(mainPath, serviceName string) error {
	raw, err := os.ReadFile(mainPath)
	if err != nil {
		return fmt.Errorf("read file: %w", err)
	}
	text := string(raw)

	if strings.Contains(text, "WrapWithPersistence(") {
		return nil
	}

	oldBlock := "\thttptransport.RegisterHandlers(mux)\n\n\taddr := \":\" + envOrDefault(\"SERVER_PORT\", \"8080\")"
	newBlock := fmt.Sprintf(
		"\thttptransport.RegisterHandlers(mux)\n\n\thandler, err := httptransport.WrapWithPersistence(%q, mux)\n\tif err != nil {\n\t\tlog.Fatalf(\"failed to initialize persistence: %%v\", err)\n\t}\n\n\taddr := \":\" + envOrDefault(\"SERVER_PORT\", \"8080\")",
		serviceName,
	)
	if !strings.Contains(text, oldBlock) {
		return fmt.Errorf("register handlers block not found")
	}
	text = strings.Replace(text, oldBlock, newBlock, 1)

	oldListen := "if err := http.ListenAndServe(addr, mux); err != nil {"
	newListen := "if err := http.ListenAndServe(addr, handler); err != nil {"
	if !strings.Contains(text, oldListen) {
		return fmt.Errorf("listen block not found")
	}
	text = strings.Replace(text, oldListen, newListen, 1)

	return os.WriteFile(mainPath, []byte(text), 0o644)
}

func loadRuntimeTemplate(root string) (string, error) {
	templatePath := filepath.Join(root, "scripts", "dev", "persistence_runtime_template.go.txt")
	if raw, err := os.ReadFile(templatePath); err == nil {
		text := strings.TrimSpace(string(raw))
		if text != "" {
			return text + "\n", nil
		}
	}
	if strings.TrimSpace(runtimeTemplate) == "" {
		return "", fmt.Errorf("template file not found: %s", templatePath)
	}
	return runtimeTemplate, nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

const runtimeTemplate = `package httptransport

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const persistenceBodyLimitBytes = 8 * 1024 * 1024

type persistenceMiddleware struct {
	service string
	strict  bool
	backend *persistenceBackend
	next    http.Handler
	mu      sync.Mutex
}

type persistenceBackend struct {
	service     string
	dbName      string
	dbUser      string
	dbPassword  string
	composeFile string
	timeout     time.Duration
}

type persistenceEvent struct {
	Method       string
	Path         string
	Query        string
	StatusCode   int
	ActorID      string
	TraceID      string
	RequestJSON  []byte
	ResponseJSON []byte
	OccurredAt   time.Time
	Links        []entityLink
}

type entityLink struct {
	SourceEntity string
	RelationKey  string
	TargetEntity string
}

func WrapWithPersistence(service string, next http.Handler) (http.Handler, error) {
	if next == nil {
		return nil, fmt.Errorf("persistence middleware requires non-nil next handler")
	}

	enabled := persistenceBoolEnvOrDefault("PERSISTENCE_ENABLED", true)
	if !enabled {
		return next, nil
	}

	strict := persistenceBoolEnvOrDefault("PERSISTENCE_STRICT", true)
	backend, err := newPersistenceBackend(service)
	if err != nil {
		if strict {
			return nil, err
		}
		log.Printf("persistence disabled for %s: %v", service, err)
		return next, nil
	}

	if err := backend.ensureSchema(); err != nil {
		if strict {
			return nil, fmt.Errorf("prepare persistence schema: %w", err)
		}
		log.Printf("persistence schema failed for %s: %v", service, err)
		return next, nil
	}

	rawState, err := backend.loadState()
	if err != nil {
		if strict {
			return nil, fmt.Errorf("load persisted state: %w", err)
		}
		log.Printf("state load failed for %s: %v", service, err)
	} else if len(rawState) > 0 {
		if err := restorePersistedState(rawState); err != nil {
			if strict {
				return nil, fmt.Errorf("restore persisted state: %w", err)
			}
			log.Printf("state restore failed for %s: %v", service, err)
		}
	}

	log.Printf("persistence enabled for %s (db=%s)", service, backend.dbName)
	return &persistenceMiddleware{
		service: service,
		strict:  strict,
		backend: backend,
		next:    next,
	}, nil
}

func (m *persistenceMiddleware) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if !persistenceIsMutatingMethod(r.Method) {
		m.next.ServeHTTP(w, r)
		return
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	requestBody, err := persistenceReadBody(r.Body)
	if err != nil {
		persistenceWriteJSONError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	r.Body = io.NopCloser(bytes.NewReader(requestBody))

	preState, err := capturePersistedState()
	if err != nil {
		persistenceWriteJSONError(w, http.StatusInternalServerError, "failed to capture pre-write state")
		return
	}

	recorder := newBufferedResponseWriter()
	m.next.ServeHTTP(recorder, r)
	if recorder.statusCode() >= http.StatusBadRequest {
		recorder.WriteTo(w)
		return
	}

	postState, err := capturePersistedState()
	if err != nil {
		_ = restorePersistedState(preState)
		persistenceWriteJSONError(w, http.StatusServiceUnavailable, "failed to capture post-write state")
		return
	}

	requestJSON := persistenceNormalizeJSON(requestBody)
	responseJSON := persistenceNormalizeJSON(recorder.BodyBytes())
	event := persistenceEvent{
		Method:       r.Method,
		Path:         r.URL.Path,
		Query:        r.URL.RawQuery,
		StatusCode:   recorder.statusCode(),
		ActorID:      strings.TrimSpace(r.Header.Get("X-User-ID")),
		TraceID:      strings.TrimSpace(r.Header.Get("X-Trace-ID")),
		RequestJSON:  requestJSON,
		ResponseJSON: responseJSON,
		OccurredAt:   time.Now().UTC(),
		Links:        persistenceExtractLinks(m.service, requestJSON, responseJSON),
	}

	if err := m.backend.persist(postState, event); err != nil {
		restoreErr := restorePersistedState(preState)
		if restoreErr != nil {
			log.Printf("persistence rollback failed for %s: %v", m.service, restoreErr)
		}
		if m.strict {
			persistenceWriteJSONError(w, http.StatusServiceUnavailable, "failed to persist data")
			return
		}
		log.Printf("persistence write failed for %s: %v", m.service, err)
	}

	recorder.WriteTo(w)
}

func newPersistenceBackend(service string) (*persistenceBackend, error) {
	service = strings.TrimSpace(service)
	if service == "" {
		return nil, fmt.Errorf("service name is required")
	}

	composeFile, err := persistenceResolveComposeFile()
	if err != nil {
		return nil, err
	}

	return &persistenceBackend{
		service:     service,
		dbName:      persistenceResolveDBName(service),
		dbUser:      persistenceEnvOrDefault("DB_USER", persistenceEnvOrDefault("POSTGRES_USER", "kis")),
		dbPassword:  persistenceEnvOrDefault("DB_PASSWORD", persistenceEnvOrDefault("POSTGRES_PASSWORD", "")),
		composeFile: composeFile,
		timeout:     persistenceDurationEnvOrDefault("PERSISTENCE_TIMEOUT", 20*time.Second),
	}, nil
}

func (b *persistenceBackend) ensureSchema() error {
	schemaSQL := "CREATE TABLE IF NOT EXISTS kis_service_state (\n" +
		"    service TEXT PRIMARY KEY,\n" +
		"    state_json JSONB NOT NULL,\n" +
		"    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n" +
		");\n" +
		"CREATE TABLE IF NOT EXISTS kis_http_journal (\n" +
		"    id BIGSERIAL PRIMARY KEY,\n" +
		"    service TEXT NOT NULL,\n" +
		"    method TEXT NOT NULL,\n" +
		"    path TEXT NOT NULL,\n" +
		"    query TEXT NOT NULL DEFAULT '',\n" +
		"    actor_id TEXT NOT NULL DEFAULT '',\n" +
		"    trace_id TEXT NOT NULL DEFAULT '',\n" +
		"    request_json JSONB,\n" +
		"    response_json JSONB,\n" +
		"    status_code INTEGER NOT NULL,\n" +
		"    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n" +
		");\n" +
		"CREATE INDEX IF NOT EXISTS idx_kis_http_journal_service_time ON kis_http_journal(service, occurred_at DESC);\n" +
		"CREATE TABLE IF NOT EXISTS kis_entity_links (\n" +
		"    id BIGSERIAL PRIMARY KEY,\n" +
		"    service TEXT NOT NULL,\n" +
		"    source_entity TEXT NOT NULL,\n" +
		"    relation_key TEXT NOT NULL,\n" +
		"    target_entity TEXT NOT NULL,\n" +
		"    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n" +
		");\n" +
		"CREATE INDEX IF NOT EXISTS idx_kis_entity_links_service_source ON kis_entity_links(service, source_entity);\n" +
		"CREATE INDEX IF NOT EXISTS idx_kis_entity_links_target ON kis_entity_links(target_entity);\n"
	_, err := b.runPSQL(schemaSQL, false)
	return err
}

func (b *persistenceBackend) loadState() ([]byte, error) {
	query := fmt.Sprintf(
		"SELECT encode(convert_to(state_json::text, 'UTF8'), 'base64') FROM kis_service_state WHERE service=%s LIMIT 1;",
		persistenceSQLQuote(b.service),
	)
	out, err := b.runPSQL(query, true)
	if err != nil {
		return nil, err
	}
	line := persistenceLastValueLine(out)
	if line == "" {
		return nil, nil
	}
	decoded, err := base64.StdEncoding.DecodeString(line)
	if err != nil {
		return nil, fmt.Errorf("decode persisted state: %w", err)
	}
	return decoded, nil
}

func (b *persistenceBackend) persist(state []byte, event persistenceEvent) error {
	if len(state) == 0 {
		return fmt.Errorf("empty persisted state")
	}

	var sql strings.Builder
	sql.WriteString("BEGIN;")
	sql.WriteString("INSERT INTO kis_service_state(service, state_json, updated_at) VALUES(")
	sql.WriteString(persistenceSQLQuote(b.service))
	sql.WriteString(", ")
	sql.WriteString(persistenceJSONExprFromBytes(state))
	sql.WriteString(", NOW()) ON CONFLICT(service) DO UPDATE SET state_json=EXCLUDED.state_json, updated_at=NOW();")

	sql.WriteString("INSERT INTO kis_http_journal(service, method, path, query, actor_id, trace_id, request_json, response_json, status_code, occurred_at) VALUES(")
	sql.WriteString(persistenceSQLQuote(b.service))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.Method))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.Path))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.Query))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.ActorID))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.TraceID))
	sql.WriteString(", ")
	sql.WriteString(persistenceJSONExprFromBytes(event.RequestJSON))
	sql.WriteString(", ")
	sql.WriteString(persistenceJSONExprFromBytes(event.ResponseJSON))
	sql.WriteString(", ")
	sql.WriteString(strconv.Itoa(event.StatusCode))
	sql.WriteString(", ")
	sql.WriteString(persistenceSQLQuote(event.OccurredAt.Format(time.RFC3339Nano)))
	sql.WriteString("::timestamptz);")

	if len(event.Links) > 0 {
		sql.WriteString("INSERT INTO kis_entity_links(service, source_entity, relation_key, target_entity, occurred_at) VALUES ")
		for i, link := range event.Links {
			if i > 0 {
				sql.WriteString(", ")
			}
			sql.WriteString("(")
			sql.WriteString(persistenceSQLQuote(b.service))
			sql.WriteString(", ")
			sql.WriteString(persistenceSQLQuote(link.SourceEntity))
			sql.WriteString(", ")
			sql.WriteString(persistenceSQLQuote(link.RelationKey))
			sql.WriteString(", ")
			sql.WriteString(persistenceSQLQuote(link.TargetEntity))
			sql.WriteString(", ")
			sql.WriteString(persistenceSQLQuote(event.OccurredAt.Format(time.RFC3339Nano)))
			sql.WriteString("::timestamptz)")
		}
		sql.WriteString(";")
	}
	sql.WriteString("COMMIT;")

	_, err := b.runPSQL(sql.String(), false)
	return err
}

func (b *persistenceBackend) runPSQL(sqlText string, query bool) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), b.timeout)
	defer cancel()

	args := []string{
		"compose", "--ansi", "never",
		"-f", b.composeFile,
		"exec", "-T", "postgres",
		"psql",
		"-v", "ON_ERROR_STOP=1",
		"-U", b.dbUser,
		"-d", b.dbName,
	}
	if query {
		args = append(args, "-q", "-t", "-A", "-X")
	} else {
		args = append(args, "-q", "-X")
	}
	args = append(args, "-f", "-")

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Stdin = strings.NewReader(sqlText)
	cmd.Env = os.Environ()
	if b.dbPassword != "" {
		cmd.Env = append(cmd.Env, "PGPASSWORD="+b.dbPassword)
	}

	output, err := cmd.CombinedOutput()
	if ctx.Err() == context.DeadlineExceeded {
		return "", fmt.Errorf("psql command timeout after %s", b.timeout)
	}
	if err != nil {
		return "", fmt.Errorf("psql command failed: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return strings.TrimSpace(string(output)), nil
}

type bufferedResponseWriter struct {
	header http.Header
	body   bytes.Buffer
	status int
}

func newBufferedResponseWriter() *bufferedResponseWriter {
	return &bufferedResponseWriter{
		header: make(http.Header),
	}
}

func (w *bufferedResponseWriter) Header() http.Header {
	return w.header
}

func (w *bufferedResponseWriter) Write(data []byte) (int, error) {
	if w.status == 0 {
		w.status = http.StatusOK
	}
	return w.body.Write(data)
}

func (w *bufferedResponseWriter) WriteHeader(statusCode int) {
	if w.status == 0 {
		w.status = statusCode
	}
}

func (w *bufferedResponseWriter) statusCode() int {
	if w.status == 0 {
		return http.StatusOK
	}
	return w.status
}

func (w *bufferedResponseWriter) BodyBytes() []byte {
	return w.body.Bytes()
}

func (w *bufferedResponseWriter) WriteTo(dst http.ResponseWriter) {
	for key, values := range w.header {
		for _, value := range values {
			dst.Header().Add(key, value)
		}
	}
	dst.WriteHeader(w.statusCode())
	_, _ = dst.Write(w.body.Bytes())
}

func persistenceReadBody(body io.ReadCloser) ([]byte, error) {
	defer body.Close()
	limited := io.LimitReader(body, persistenceBodyLimitBytes+1)
	raw, err := io.ReadAll(limited)
	if err != nil {
		return nil, err
	}
	if len(raw) > persistenceBodyLimitBytes {
		return nil, fmt.Errorf("body is too large")
	}
	return raw, nil
}

func persistenceNormalizeJSON(raw []byte) []byte {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		return nil
	}

	var value any
	if err := json.Unmarshal(trimmed, &value); err != nil {
		return nil
	}

	normalized, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	return normalized
}

func persistenceWriteJSONError(w http.ResponseWriter, status int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": message})
}

func persistenceIsMutatingMethod(method string) bool {
	switch strings.ToUpper(strings.TrimSpace(method)) {
	case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
		return true
	default:
		return false
	}
}

func persistenceExtractLinks(service string, requestJSON, responseJSON []byte) []entityLink {
	reqValue := persistenceDecodeJSON(requestJSON)
	respValue := persistenceDecodeJSON(responseJSON)

	sourceID := persistenceFindPrimaryID(respValue)
	if sourceID == "" {
		sourceID = persistenceFindPrimaryID(reqValue)
	}
	if sourceID == "" {
		return nil
	}

	candidates := make(map[string]string)
	persistenceCollectRelationCandidates(reqValue, candidates)
	persistenceCollectRelationCandidates(respValue, candidates)

	links := make([]entityLink, 0, len(candidates))
	seen := make(map[string]bool)
	sourceEntity := service + ":" + sourceID

	for key, value := range candidates {
		if key == "id" || strings.TrimSpace(value) == "" {
			continue
		}
		targetDomain := persistenceGuessDomainForKey(key)
		targetEntity := ""
		if targetDomain == "" {
			targetEntity = key + ":" + value
		} else {
			targetEntity = targetDomain + ":" + value
		}
		if targetEntity == sourceEntity {
			continue
		}

		dedup := key + "|" + targetEntity
		if seen[dedup] {
			continue
		}
		seen[dedup] = true
		links = append(links, entityLink{
			SourceEntity: sourceEntity,
			RelationKey:  key,
			TargetEntity: targetEntity,
		})
	}

	sort.Slice(links, func(i, j int) bool {
		if links[i].RelationKey == links[j].RelationKey {
			return links[i].TargetEntity < links[j].TargetEntity
		}
		return links[i].RelationKey < links[j].RelationKey
	})
	return links
}

func persistenceDecodeJSON(raw []byte) any {
	if len(raw) == 0 {
		return nil
	}
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil
	}
	return value
}

func persistenceFindPrimaryID(value any) string {
	switch typed := value.(type) {
	case map[string]any:
		if id, ok := typed["id"].(string); ok {
			id = strings.TrimSpace(id)
			if id != "" {
				return id
			}
		}
		for _, nested := range typed {
			if id := persistenceFindPrimaryID(nested); id != "" {
				return id
			}
		}
	case []any:
		for _, nested := range typed {
			if id := persistenceFindPrimaryID(nested); id != "" {
				return id
			}
		}
	}
	return ""
}

func persistenceCollectRelationCandidates(value any, out map[string]string) {
	switch typed := value.(type) {
	case map[string]any:
		for key, nested := range typed {
			normalizedKey := strings.ToLower(strings.TrimSpace(key))
			if persistenceIsRelationKey(normalizedKey) {
				if str, ok := nested.(string); ok {
					str = strings.TrimSpace(str)
					if str != "" {
						out[normalizedKey] = str
					}
				}
			}
			persistenceCollectRelationCandidates(nested, out)
		}
	case []any:
		for _, nested := range typed {
			persistenceCollectRelationCandidates(nested, out)
		}
	}
}

func persistenceIsRelationKey(key string) bool {
	if key == "id" {
		return true
	}
	if strings.HasSuffix(key, "_id") {
		return true
	}
	switch key {
	case "vin", "vehicle_vin", "reserved_vin":
		return true
	default:
		return false
	}
}

func persistenceGuessDomainForKey(key string) string {
	switch key {
	case "client_id", "contact_id":
		return "crm-contacts"
	case "lead_id":
		return "crm-leads"
	case "deal_id":
		return "sales-deals"
	case "document_id", "sales_document_id":
		return "sales-documents"
	case "owner_id", "user_id", "actor_id", "technician_id", "advisor_id":
		return "identity-access"
	case "appointment_id":
		return "service-appointments"
	case "workorder_id", "work_order_id":
		return "service-workorders"
	case "invoice_id":
		return "finance-invoicing"
	case "ledger_id":
		return "finance-ledger"
	case "vendor_id", "supplier_id":
		return "inventory-procurement"
	case "part_id", "item_id", "stock_item_id", "vin", "vehicle_vin", "reserved_vin":
		return "inventory-stock"
	default:
		return ""
	}
}

func persistenceResolveComposeFile() (string, error) {
	if explicit := strings.TrimSpace(os.Getenv("KIS_DOCKER_COMPOSE_FILE")); explicit != "" {
		if persistenceFileExists(explicit) {
			return explicit, nil
		}
		return "", fmt.Errorf("KIS_DOCKER_COMPOSE_FILE does not exist: %s", explicit)
	}

	candidates := make([]string, 0)
	if dockerDir := strings.TrimSpace(os.Getenv("KIS_DOCKER_DIR")); dockerDir != "" {
		candidates = append(candidates, filepath.Join(dockerDir, "docker-compose.yml"))
	}

	if cwd, err := os.Getwd(); err == nil {
		if root := persistenceFindRoot(cwd); root != "" {
			candidates = append(candidates, filepath.Join(root, "infra", "docker", "docker-compose.yml"))
		}
		candidates = append(candidates, filepath.Clean(filepath.Join(cwd, "..", "..", "infra", "docker", "docker-compose.yml")))
	}

	if exePath, err := os.Executable(); err == nil {
		if root := persistenceFindRoot(filepath.Dir(exePath)); root != "" {
			candidates = append(candidates, filepath.Join(root, "infra", "docker", "docker-compose.yml"))
		}
	}

	seen := map[string]bool{}
	for _, candidate := range candidates {
		candidate = filepath.Clean(candidate)
		if seen[candidate] {
			continue
		}
		seen[candidate] = true
		if persistenceFileExists(candidate) {
			return candidate, nil
		}
	}

	return "", fmt.Errorf("docker-compose.yml not found; set KIS_DOCKER_COMPOSE_FILE or KIS_DOCKER_DIR")
}

func persistenceFindRoot(start string) string {
	current := filepath.Clean(start)
	for {
		if persistenceFileExists(filepath.Join(current, "go.work")) {
			return current
		}
		parent := filepath.Dir(current)
		if parent == current {
			return ""
		}
		current = parent
	}
}

func persistenceResolveDBName(service string) string {
	if value := strings.TrimSpace(os.Getenv("DB_NAME")); value != "" {
		return value
	}
	if rawURL := strings.TrimSpace(os.Getenv("DATABASE_URL")); rawURL != "" {
		parsed, err := url.Parse(rawURL)
		if err == nil {
			name := strings.TrimSpace(strings.TrimPrefix(parsed.Path, "/"))
			if name != "" {
				return name
			}
		}
	}
	return strings.ReplaceAll(strings.ToLower(strings.TrimSpace(service)), "-", "_")
}

func persistenceFileExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return !info.IsDir()
}

func persistenceEnvOrDefault(key, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

func persistenceBoolEnvOrDefault(key string, fallback bool) bool {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseBool(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func persistenceDurationEnvOrDefault(key string, fallback time.Duration) time.Duration {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := time.ParseDuration(value)
	if err != nil || parsed <= 0 {
		return fallback
	}
	return parsed
}

func persistenceSQLQuote(value string) string {
	escaped := strings.ReplaceAll(value, "'", "''")
	return "'" + escaped + "'"
}

func persistenceJSONExprFromBytes(raw []byte) string {
	if len(raw) == 0 {
		return "NULL"
	}
	encoded := base64.StdEncoding.EncodeToString(raw)
	return "convert_from(decode('" + encoded + "', 'base64'), 'UTF8')::jsonb"
}

func persistenceLastValueLine(output string) string {
	lines := strings.Split(output, "\n")
	for i := len(lines) - 1; i >= 0; i-- {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			continue
		}
		if strings.HasPrefix(strings.ToUpper(line), "WARNING:") {
			continue
		}
		if strings.HasPrefix(strings.ToUpper(line), "WARN[") {
			continue
		}
		return line
	}
	return ""
}
`
