package httptransport

import (
	"encoding/json"
	"fmt"
)

// Code generated by scripts/dev/generate_persistence_layer.go; DO NOT EDIT.
type persistedState struct {
	MartsStore martsStorePersistedState `json:"martsStore"`
}

type martsStorePersistedState struct {
	SnapshotSeq int `json:"snapshotSeq"`
	ComplianceSeq int `json:"complianceSeq"`
	EventSeq int `json:"eventSeq"`
	Snapshots []martSnapshot `json:"snapshots"`
	Compliance []complianceRun `json:"compliance"`
	Events []martEvent `json:"events"`
}

func capturePersistedState() ([]byte, error) {
	state := persistedState{}
	martsStore.RLock()
	state.MartsStore = martsStorePersistedState{
		SnapshotSeq: martsStore.snapshotSeq,
		ComplianceSeq: martsStore.complianceSeq,
		EventSeq: martsStore.eventSeq,
		Snapshots: martsStore.snapshots,
		Compliance: martsStore.compliance,
		Events: martsStore.events,
	}
	martsStore.RUnlock()
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal persisted state: %w", err)
	}
	return raw, nil
}

func restorePersistedState(raw []byte) error {
	if len(raw) == 0 {
		return nil
	}

	var state persistedState
	if err := json.Unmarshal(raw, &state); err != nil {
		return fmt.Errorf("unmarshal persisted state: %w", err)
	}
	martsStore.Lock()
	martsStore.snapshotSeq = state.MartsStore.SnapshotSeq
	martsStore.complianceSeq = state.MartsStore.ComplianceSeq
	martsStore.eventSeq = state.MartsStore.EventSeq
	martsStore.snapshots = state.MartsStore.Snapshots
	martsStore.compliance = state.MartsStore.Compliance
	martsStore.events = state.MartsStore.Events
	martsStore.Unlock()
	return nil
}

func resetPersistedState() {
	var state persistedState
	martsStore.Lock()
	martsStore.snapshotSeq = state.MartsStore.SnapshotSeq
	martsStore.complianceSeq = state.MartsStore.ComplianceSeq
	martsStore.eventSeq = state.MartsStore.EventSeq
	martsStore.snapshots = state.MartsStore.Snapshots
	martsStore.compliance = state.MartsStore.Compliance
	martsStore.events = state.MartsStore.Events
	martsStore.Unlock()
}
